select * from customer;

-- what is the total revenue generated by male vs female customers
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

--which customers used a discount but still spent more than average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);

--which are the top 5 products based on the average review ratings
select item_purchased,round(avg(review_rating::numeric),2) as average_rating
from customer
group by item_purchased
order by average_rating desc
limit 5;

--Compare the average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2) as average_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--do subscribed customer spend more?
select subscription_status,
count(customer_id) as total_customers,
sum(purchase_amount) as total_revenue,
round(avg(purchase_amount),2) as average_spend
from customer
group by subscription_status
order by total_revenue,average_spend desc;

--which 5 products have the highest percentage of purchases with discount applied
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--what are the top 3 products purchased in each category
with new_table as(select item_purchased,category,count(customer_id) as total,
dense_rank() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by item_purchased,category
order by total)

select *
from new_table
where item_rank <= 3;

--what are revenue contribution by each age group
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;


